// Master Category data - maps directly to sections_items_full.json
export type MasterCategory = {
    code: string;      // Section code (P01, P02, etc.)
    label: string;     // Display label
    icon?: string;     // Optional emoji icon
};

export const masterCategories: MasterCategory[] = [
    { code: 'P01', label: 'Fresh Produce', icon: '🥬' },
    { code: 'P02', label: 'Grocery, Staples & Packaged Foods', icon: '🛒' },
    { code: 'P03', label: 'Dairy, Bakery & Eggs', icon: '🥛' },
    { code: 'P04', label: 'Meat, Seafood & Frozen', icon: '🥩' },
    { code: 'P05', label: 'Beverages (Non-Alcoholic)', icon: '🥤' },
    { code: 'P06', label: 'Alcoholic Beverages', icon: '🍷' },
    { code: 'P07', label: 'Tobacco & Smoking (18+)', icon: '🚬' },
    { code: 'P08', label: 'Personal Care, Beauty & Grooming', icon: '💄' },
    { code: 'P09', label: 'Health, OTC & Pharmacy', icon: '💊' },
    { code: 'P10', label: 'Baby, Kids & Maternity', icon: '👶' },
    { code: 'P11', label: 'Pet & Veterinary', icon: '🐕' },
    { code: 'P12', label: 'Home Care & Cleaning', icon: '🧹' },
    { code: 'P13', label: 'Kitchenware, Cookware & Dining', icon: '🍳' },
    { code: 'P14', label: 'Home & Living (Furnishings & Décor)', icon: '🛋️' },
    { code: 'P15', label: 'Furniture & Mattresses', icon: '🛏️' },
    { code: 'P16', label: 'Event, Wedding & Décor', icon: '💒' },
    { code: 'P17', label: 'Stationery, Art & Office Supplies', icon: '✏️' },
    { code: 'P18', label: 'Books, Media & Hobbies', icon: '📚' },
    { code: 'P19', label: 'Toys, Kids Hobbies & Party', icon: '🧸' },
    { code: 'P20', label: 'Sports, Fitness & Outdoors', icon: '⚽' },
    { code: 'P21', label: 'Musical Instruments & Pro Audio', icon: '🎸' },
    { code: 'P22', label: 'Mobiles, Computers & Accessories', icon: '📱' },
    { code: 'P23', label: 'Consumer Electronics & Entertainment', icon: '📺' },
    { code: 'P24', label: 'Cameras & Surveillance Drones', icon: '📷' },
    { code: 'P25', label: 'Smart Home & IoT', icon: '🏠' },
    { code: 'P26', label: 'Large Appliances', icon: '🧊' },
    { code: 'P27', label: 'Electricals & Lighting', icon: '💡' },
    { code: 'P28', label: 'Power Backup, Solar & Energy', icon: '🔋' },
    { code: 'P29', label: 'Tools, Hardware & Home Improvement', icon: '🔧' },
    { code: 'P30', label: 'Building & Construction Materials', icon: '🏗️' },
    { code: 'P31', label: 'Paints, Chemicals & Surface Care', icon: '🎨' },
    { code: 'P32', label: 'Industrial, MRO & Safety', icon: '🏭' },
    { code: 'P33', label: 'Packaging, Printing & Signage', icon: '📦' },
    { code: 'P34', label: 'Raw Materials & Commodities (B2B)', icon: '⚙️' },
    { code: 'P35', label: 'Automotive & Two-Wheelers', icon: '🚗' },
    { code: 'P36', label: 'EV & e-Mobility', icon: '🔌' },
    { code: 'P37', label: 'Luggage, Travel & Outdoor Gear', icon: '🧳' },
    { code: 'P38', label: 'Watches, Jewellery & Precious', icon: '💎' },
    { code: 'P39', label: 'Fashion – Men', icon: '👔' },
    { code: 'P40', label: 'Fashion – Women', icon: '👗' },
    { code: 'P41', label: 'Fashion – Kids & Infants', icon: '👕' },
    { code: 'P42', label: 'Footwear', icon: '👟' },
    { code: 'P43', label: 'Apparel Materials, Tailoring & Accessories', icon: '🧵' },
    { code: 'P44', label: 'Religious, Puja & Festive', icon: '🪔' },
    { code: 'P45', label: 'Handloom, Handicrafts & Ethnic Specialties', icon: '🎭' },
    { code: 'P46', label: 'Medical & Hospital Equipment', icon: '🏥' },
    { code: 'P47', label: 'Education, Lab & Scientific', icon: '🔬' },
    { code: 'P48', label: 'Agriculture, Gardening & Irrigation', icon: '🌾' },
    { code: 'P49', label: 'Digital Goods & Gift Cards', icon: '🎁' },
    { code: 'P50', label: 'Winter & Seasonal Utilities', icon: '❄️' },
    { code: 'P51', label: 'Household Services Consumables', icon: '🏠' },
    { code: 'P52', label: 'Safety, Security & Surveillance', icon: '🔒' },
];
